---
  - hosts: server
    become: true
    gather_facts: no
    tasks: 
      - name: Install base packages
        raw: name={{ item }} state=installed
        with_items:
          - python3
          - python3-pip
          - docker-py

      - name: Build Image
        docker_image: 
          path: ~/CP-Devops-Assignment/Dockerfile
          name: webapp

      - name: Run Container
        docker_continer: 
          name: webapp
          image: webapp
          state: started
          ports:
           - "8080:8080"
          tty: true
          detached: true
          
       - name: validate
         uri: 
           url: http://localhost:8080/sample
           return_content: yes
           register: this
           faild_when: "''not in this content"
           
     




